host:        127.0.0.1
port:        4000

name:        "Void Linux for PowerPC/Power ISA (unofficial)"
markdown:    kramdown
highlighter: rouge

permalink:   /news/:year/:month/:title.html

snow:        0

gems:
  - jekyll-redirect-from
